import { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { QRCodeSVG } from 'qrcode.react';
import { formatDateTime } from '../../utils/parkingUtils';
import { generateUPILink } from '../../utils/parkingUtils';
import { loadVehicleSession, listenPaymentStatus, submitPaymentReference } from '../../services/userParkingService';

export default function UserPaymentPage() {
  const location = useLocation(); const navigate = useNavigate(); const query = new URLSearchParams(location.search);
  const stored = (() => { try { return JSON.parse(sessionStorage.getItem('velox_payment_session') || '{}'); } catch { return {}; } })();
  const plate = query.get('plate') || stored.plate; const sessionId = query.get('sessionId') || stored.sessionId;
  const [session, setSession] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [mode, setMode] = useState('awaiting_payment'); const [refId, setRefId] = useState(''); const [submitting, setSubmitting] = useState(false); const [expiresAt, setExpiresAt] = useState(Date.now() + 10 * 60 * 1000); const [remaining, setRemaining] = useState(600);
  const [config, setConfig] = useState({ upiId: '', upiName: 'VeloxPark' });
  useEffect(() => { fetch('/config.json').then((res) => res.json()).then((value) => setConfig((old) => ({ ...old, ...value }))).catch(() => {}); }, []);
  useEffect(() => { if (!plate || !sessionId) { navigate('/user', { replace: true, state: { message: 'Payment session not found.' } }); return undefined; } setLoading(true); return loadVehicleSession(plate, sessionId, (value) => { setSession(value); setLoading(false); if (value.paymentStatus === 'paid') setMode('paid'); else if (value.paymentStatus === 'pending_verification') setMode('pending_verification'); else if (value.status === 'parked' || value.amount <= 0) navigate('/user', { replace: true, state: { message: 'This session does not need payment.' } }); }, () => { setLoading(false); navigate('/user', { replace: true, state: { message: 'Unable to load this payment session.' } }); }); }, [plate, sessionId, navigate]);
  useEffect(() => { if (!sessionId || sessionId.startsWith('legacy_')) return undefined; return listenPaymentStatus(sessionId, (value) => { if (value?.paymentStatus === 'paid') setMode('paid'); else if (value?.paymentStatus === 'pending_verification') setMode('pending_verification'); }, () => setError('Payment status updates are temporarily unavailable.')); }, [sessionId]);
  useEffect(() => { const timer = setInterval(() => setRemaining(Math.max(0, Math.ceil((expiresAt - Date.now()) / 1000))), 1000); return () => clearInterval(timer); }, [expiresAt]);
  const link = useMemo(() => session && config.upiId ? generateUPILink(config.upiId, config.upiName, session.amount, session.plate) : '', [config, session]);
  const submit = async (event) => { event.preventDefault(); if (!/^\d{12}$/.test(refId)) { setError('Enter the 12-digit UPI transaction/reference ID.'); return; } setSubmitting(true); setError(''); try { await submitPaymentReference({ sessionId, plate: session.plate, amount: session.amount, paymentRef: refId }); setMode('pending_verification'); } catch (err) { setError(err.message || 'Could not submit payment reference.'); } finally { setSubmitting(false); } };
  if (loading) return <main className="vp-pay-page"><section className="vp-pay-card"><h1>Loading payment…</h1><p>Rechecking the live parking session.</p></section></main>;
  if (!session) return null;
  return <main className="vp-pay-page"><section className="vp-pay-card"><button className="vp-back" type="button" onClick={() => navigate('/user')}>← Back</button><p className="vp-eyebrow">PAYMENT · {session.plate}</p><h1>Pay your parking fee</h1><div className="vp-pay-amount">₹{session.amount}</div><p>Session exited at {formatDateTime(session.exit)}.</p>
    {mode === 'paid' ? <div className="vp-pay-success"><h2>Payment verified</h2><p>Your payment is confirmed.</p><button type="button" onClick={() => navigate(`/user/payment/success?sessionId=${sessionId}&plate=${plate}`)}>View receipt</button></div> : mode === 'pending_verification' ? <div className="vp-pay-success"><h2>Waiting for verification</h2><p>Your reference was submitted. This page will update automatically after staff verifies it.</p></div> : <><p className="vp-expiry">QR expires in {Math.floor(remaining / 60)}:{String(remaining % 60).padStart(2, '0')}</p>{link ? <><div className="vp-qr"><QRCodeSVG value={link} size={220} includeMargin /></div><a className="vp-upi" href={link}>Pay with UPI app</a></> : <p className="vp-banner">UPI configuration is unavailable. Please contact staff.</p>}<button className="vp-regenerate" type="button" onClick={() => setExpiresAt(Date.now() + 10 * 60 * 1000)}>Regenerate QR</button><form onSubmit={submit} className="vp-confirm"><h2>Already paid?</h2><label htmlFor="txn">UPI transaction/reference ID</label><input id="txn" inputMode="numeric" maxLength={12} value={refId} onChange={(e) => setRefId(e.target.value.replace(/\D/g, '').slice(0, 12))} placeholder="12 digits"/><button type="submit" disabled={submitting || refId.length !== 12}>{submitting ? 'Submitting…' : 'Submit for verification'}</button></form></>}{error && <p className="vp-error" role="alert">{error}</p>}</section><style>{`.vp-pay-page{min-height:100vh;background:#0A0A0A;color:#fff;padding:32px 16px 100px;font-family:Space Mono,monospace}.vp-pay-card{max-width:560px;margin:auto;background:#161616;border:1px solid #2b2b2b;border-radius:16px;padding:24px;text-align:center}.vp-pay-card h1{font-family:Barlow Condensed,Arial Narrow,sans-serif;font-size:42px;line-height:1}.vp-eyebrow{color:#FFD700;letter-spacing:.12em;font-size:11px}.vp-back{display:block;background:none;border:0;color:#FFD700;font:inherit;min-height:44px}.vp-pay-amount{font-size:46px;color:#FFD700;font-weight:700;margin:20px}.vp-qr{background:#fff;display:inline-block;padding:12px;border-radius:10px;margin:14px}.vp-upi,.vp-pay-card button{display:block;min-height:44px;background:#FFD700;color:#0A0A0A;border:0;border-radius:10px;padding:12px 16px;font:inherit;font-weight:700;text-decoration:none;margin:12px auto}.vp-regenerate{background:transparent!important;color:#FFD700!important;border:1px solid #544d20!important}.vp-confirm{border-top:1px solid #333;margin-top:28px;padding-top:22px;text-align:left}.vp-confirm h2{font-size:18px}.vp-confirm label{display:block;margin:8px 0}.vp-confirm input{width:100%;background:#0A0A0A;border:1px solid #444;padding:13px;color:#fff;border-radius:8px;font:inherit}.vp-error{color:#FF3366}.vp-pay-success{border:1px solid #00FF88;padding:20px;border-radius:12px}.vp-pay-success h2{color:#00FF88}.vp-expiry{color:#FFD700}.vp-banner{padding:12px;color:#ffe874}`}</style></main>;
}
